# Required Environment variables
# ESA_TF_RELEASE

version: '3.8'

services:
    esa-tf-scheduler:
        image: daskdev/dask:2021.8.1-py3.9
        hostname: scheduler
        ports:
          - "8786:8786"
          - "8787:8787"
        command: dask-scheduler

    esa-tf-restapi:
        image: esa_tf_restapi:${ESA_TF_RELEASE}
        ports:
           - "8080:8080"
        command: make serve PORT=8080

    esa-tf-worker:
        image: esa_tf_worker:${ESA_TF_RELEASE}
        command: make dask-worker DASKFLAGS="tcp://scheduler:8786"
