name: restapi-on-push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
        working-directory: ./esa_tf_restapi

    steps:
    - uses: actions/checkout@v2
    - name: Cache conda
      uses: actions/cache@v2
      with:
        path: ~/conda_pkgs_dir
        key:
          ubuntu-latest-3.8
    - uses: conda-incubator/setup-miniconda@v2
      with:
        channels: conda-forge
        channel-priority: strict
        mamba-version: "*"
        activate-environment: ubuntu-latest-3.8
        auto-update-conda: false
        python-version: 3.8
        use-only-tar-bz2: true
    - name: Install dependencies
      run: |
        make conda-env-create && conda init bash && source ~/.bashrc && conda activate ESA_TF_RESTAPI
    - name: Install esa_tf_restapi
      run: |
        python -m pip install --no-deps -e .
    - name: Run unit tests
      run: |
        make test COV_REPORT=xml
    - name: Upload code coverage to Codecov
      uses: codecov/codecov-action@v1

  code-quality:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
        working-directory: ./esa_tf_restapi

    steps:
    - uses: actions/checkout@v2
    - name: Cache conda
      uses: actions/cache@v2
      with:
        path: ~/conda_pkgs_dir
        key:
          ubuntu-latest-3.8
    - uses: conda-incubator/setup-miniconda@v2
      with:
        channels: conda-forge
        channel-priority: strict
        mamba-version: "*"
        activate-environment: ubuntu-latest-3.8
        auto-update-conda: false
        python-version: 3.8
        use-only-tar-bz2: true
    - name: Install dependencies
      run: |
        make conda-env-create && conda init bash && source ~/.bashrc && conda activate ESA_TF_RESTAPI
    - name: Install esa_tf_restapi
      run: |
        python -m pip install --no-deps -e .
    - name: Lint with flake8
      run: |
        make code-quality

  code-style:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./esa_tf_restapi

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        make conda-env-create && conda init bash && source ~/.bashrc && conda activate ESA_TF_RESTAPI
    - name: Check code style with black
      run: |
        make code-style