name: restapi-on-push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
        working-directory: ./esa_tf_restapi

    steps:
    - uses: actions/checkout@v2
    - name: Cache conda
      uses: actions/cache@v2
      with:
        path: ~/conda_pkgs_dir
        key:
          ubuntu-latest-3.9
    - name: Install Conda environment with Micromamba
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: environment.yml
        environment-name: ubuntu-latest-3.9
        cache-environment: true
    - name: Install package
      run: |
        python -m pip install --no-deps -e .
    - name: Run unit tests
      run: |
        make test COV_REPORT=xml

  code-quality:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
        working-directory: ./esa_tf_restapi

    steps:
    - uses: actions/checkout@v2
    - name: Cache conda
      uses: actions/cache@v2
      with:
        path: ~/conda_pkgs_dir
        key:
          ubuntu-latest-3.9
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: ubuntu-latest-3.9
        auto-update-conda: false
        python-version: 3.9
        use-only-tar-bz2: true
    - name: Install dependencies
      run: |
        make conda-env-update ENVIRONMENT=ubuntu-latest-3.9
    - name: Lint with flake8
      run: |
        make code-quality

  code-style:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./esa_tf_restapi

    steps:
    - uses: actions/checkout@v2
    - name: Check code style with black
      run: |
        $CONDA/bin/conda install black
        $CONDA/bin/black --check .
    - name: Check code style with isort
      run: |
        $CONDA/bin/conda install isort
        $CONDA/bin/isort --check .
    - name: Check documentation style with mdformat
      run: |
        $CONDA/bin/conda install -c conda-forge mdformat
        $CONDA/bin/mdformat --check .
